"use server";

// List of 88 healthcare professions matching our salary data
export async function getHealthcareProfessions() {
    return [
        { slug: "registered-nurses", name: "Registered Nurses" },
        { slug: "nurse-practitioners", name: "Nurse Practitioners" },
        { slug: "licensed-practical-and-licensed-vocational-nurses", name: "Licensed Practical/Vocational Nurses" },
        { slug: "nursing-assistants", name: "Nursing Assistants" },
        { slug: "physician-assistants", name: "Physician Assistants" },
        { slug: "physicians-and-surgeons", name: "Physicians and Surgeons" },
        { slug: "dentists-general", name: "Dentists (General)" },
        { slug: "dental-hygienists", name: "Dental Hygienists" },
        { slug: "dental-assistants", name: "Dental Assistants" },
        { slug: "pharmacists", name: "Pharmacists" },
        { slug: "pharmacy-technicians", name: "Pharmacy Technicians" },
        { slug: "physical-therapists", name: "Physical Therapists" },
        { slug: "occupational-therapists", name: "Occupational Therapists" },
        { slug: "speech-language-pathologists", name: "Speech-Language Pathologists" },
        { slug: "respiratory-therapists", name: "Respiratory Therapists" },
        { slug: "radiologic-technologists-and-technicians", name: "Radiologic Technologists" },
        { slug: "diagnostic-medical-sonographers", name: "Diagnostic Medical Sonographers" },
        { slug: "medical-assistants", name: "Medical Assistants" },
        { slug: "phlebotomists", name: "Phlebotomists" },
        { slug: "clinical-laboratory-technologists-and-technicians", name: "Clinical Laboratory Technologists" },
        { slug: "emergency-medical-technicians", name: "Emergency Medical Technicians (EMTs)" },
        { slug: "paramedics", name: "Paramedics" },
        { slug: "surgical-technologists", name: "Surgical Technologists" },
        { slug: "medical-records-specialists", name: "Medical Records Specialists" },
        { slug: "health-information-technicians", name: "Health Information Technicians" },
        { slug: "chiropractors", name: "Chiropractors" },
        { slug: "optometrists", name: "Optometrists" },
        { slug: "podiatrists", name: "Podiatrists" },
        { slug: "veterinarians", name: "Veterinarians" },
        { slug: "dietitians-and-nutritionists", name: "Dietitians and Nutritionists" },
        { slug: "athletic-trainers", name: "Athletic Trainers" },
        { slug: "genetic-counselors", name: "Genetic Counselors" },
        { slug: "orthotists-and-prosthetists", name: "Orthotists and Prosthetists" },
        { slug: "hearing-aid-specialists", name: "Hearing Aid Specialists" },
        { slug: "audiologists", name: "Audiologists" },
        { slug: "recreational-therapists", name: "Recreational Therapists" },
        { slug: "radiation-therapists", name: "Radiation Therapists" },
        { slug: "nuclear-medicine-technologists", name: "Nuclear Medicine Technologists" },
        { slug: "cardiovascular-technologists-and-technicians", name: "Cardiovascular Technologists" },
        { slug: "magnetic-resonance-imaging-technologists", name: "MRI Technologists" },
        { slug: "medical-dosimetrists", name: "Medical Dosimetrists" },
        { slug: "ophthalmic-medical-technicians", name: "Ophthalmic Medical Technicians" },
        { slug: "psychiatric-technicians", name: "Psychiatric Technicians" },
        { slug: "veterinary-technologists-and-technicians", name: "Veterinary Technologists" },
        { slug: "home-health-and-personal-care-aides", name: "Home Health and Personal Care Aides" },
        { slug: "occupational-therapy-assistants", name: "Occupational Therapy Assistants" },
        { slug: "physical-therapist-assistants", name: "Physical Therapist Assistants" },
        { slug: "massage-therapists", name: "Massage Therapists" },
        { slug: "dental-laboratory-technicians", name: "Dental Laboratory Technicians" },
        { slug: "medical-equipment-preparers", name: "Medical Equipment Preparers" },
        { slug: "ophthalmic-laboratory-technicians", name: "Ophthalmic Laboratory Technicians" },
        { slug: "pharmacy-aides", name: "Pharmacy Aides" },
        { slug: "veterinary-assistants-and-laboratory-animal-caretakers", name: "Veterinary Assistants" },
        { slug: "medical-transcriptionists", name: "Medical Transcriptionists" },
        { slug: "healthcare-social-workers", name: "Healthcare Social Workers" },
        { slug: "mental-health-counselors", name: "Mental Health Counselors" },
        { slug: "substance-abuse-behavioral-disorder-and-mental-health-counselors", name: "Substance Abuse Counselors" },
        { slug: "health-education-specialists", name: "Health Education Specialists" },
        { slug: "clinical-laboratory-technologists-and-technicians", name: "Clinical Lab Technicians" },
        { slug: "medical-and-health-services-managers", name: "Medical and Health Services Managers" },
        { slug: "anesthesiologists", name: "Anesthesiologists" },
        { slug: "cardiologists", name: "Cardiologists" },
        { slug: "dermatologists", name: "Dermatologists" },
        { slug: "emergency-medicine-physicians", name: "Emergency Medicine Physicians" },
        { slug: "family-medicine-physicians", name: "Family Medicine Physicians" },
        { slug: "general-internal-medicine-physicians", name: "Internal Medicine Physicians" },
        { slug: "neurologists", name: "Neurologists" },
        { slug: "obstetricians-and-gynecologists", name: "Obstetricians and Gynecologists" },
        { slug: "pediatricians-general", name: "Pediatricians" },
        { slug: "psychiatrists", name: "Psychiatrists" },
        { slug: "radiologists", name: "Radiologists" },
        { slug: "surgeons-except-ophthalmologists", name: "Surgeons" },
        { slug: "orthopedic-surgeons-except-pediatric", name: "Orthopedic Surgeons" },
        { slug: "pathologists", name: "Pathologists" },
        { slug: "allergists-and-immunologists", name: "Allergists and Immunologists" },
        { slug: "general-dentists", name: "General Dentists" },
        { slug: "oral-and-maxillofacial-surgeons", name: "Oral and Maxillofacial Surgeons" },
        { slug: "orthodontists", name: "Orthodontists" },
        { slug: "prosthodontists", name: "Prosthodontists" },
        { slug: "clinical-and-counseling-psychologists", name: "Clinical Psychologists" },
        { slug: "school-psychologists", name: "School Psychologists" },
        { slug: "industrial-organizational-psychologists", name: "Industrial-Organizational Psychologists" },
        { slug: "neuropsychologists", name: "Neuropsychologists" },
        { slug: "health-informatics-specialists", name: "Health Informatics Specialists" },
        { slug: "biomedical-engineers", name: "Biomedical Engineers" },
        { slug: "medical-scientists-except-epidemiologists", name: "Medical Scientists" },
        { slug: "epidemiologists", name: "Epidemiologists" },
        { slug: "medical-appliance-technicians", name: "Medical Appliance Technicians" },
    ];
}
